Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /api/users
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Internal Server Error: /api/user/
Traceback (most recent call last):
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\serializers.py", line 738, in data
    ret = super(ListSerializer, self).data
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\serializers.py", line 656, in to_representation
    self.child.to_representation(item) for item in iterable
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\serializers.py", line 656, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\serializers.py", line 483, in to_representation
    fields = self._readable_fields
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\serializers.py", line 377, in _readable_fields
    field for field in self.fields.values()
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\serializers.py", line 993, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "E:\myWorkspace\python\DevOps\venv\lib\site-packages\rest_framework\serializers.py", line 1070, in get_field_names
    serializer_class=self.__class__.__name__
AssertionError: ("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the UserSerializer serializer.",)
Not Found: /
Not Found: /
Not Found: /
Not Found: /api-auth/login/
Not Found: /api-auth/login/
Not Found: /api-auth/login/
Not Found: /api-auth/login/
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /api/users
Not Found: /api/docs
Not Found: /accounts/login/
Not Found: /
Not Found: /favicon.ico
